import { json, type RequestHandler } from "@sveltejs/kit"
import { minecraftServerManager } from "$lib/server/minecraft-server-manager"
import { randomUUID } from "node:crypto"
import path from "node:path"
import { mkdir, writeFile } from "node:fs/promises"
import { appPaths } from "$lib/server/config"
import { getProvider } from "$lib/server/providers/registry"
import { serverDb } from "$lib/server/db"

export const GET: RequestHandler = async () => {
  return json(minecraftServerManager.listServers())
}

export const POST: RequestHandler = async ({ request }) => {
  const body = await request.json()
  const {
    name,
    providerId,
    version,
    build,
    minMem,
    maxMem,
    jvmArgs,
    port,
    offlineMode,
    maxPlayers,
    motd,
    pvp,
    seed,
    eulaAccepted,
    difficulty,
    gamemode,
    allowFlight,
    spawnProtection
  } = body as {
    name?: string
    providerId?: string
    version?: string
    build?: string
    minMem?: string
    maxMem?: string
    jvmArgs?: string
    port?: number
    offlineMode?: boolean
    maxPlayers?: number
    motd?: string
    pvp?: boolean
    seed?: string
    eulaAccepted?: boolean
    difficulty?: "easy" | "normal" | "hard" | "peaceful"
    gamemode?: "survival" | "creative" | "adventure" | "spectator"
    allowFlight?: boolean
    spawnProtection?: number
  }

  if (!name || !providerId || !version || !build) {
    return json({ error: "Missing required fields: name, providerId, version, build" }, { status: 400 })
  }
  if (!eulaAccepted) {
    return json({ error: "You must accept Mojang EULA to create a server." }, { status: 400 })
  }

  const provider = getProvider(providerId)
  if (!provider) {
    return json({ error: `Unknown provider: ${providerId}` }, { status: 404 })
  }

  const id = randomUUID()
  const serverPath = path.join(appPaths.servers, id)
  const jarPath = path.join(serverPath, "server.jar")
  const normalizedPort = Number.isInteger(port) ? Number(port) : 25565
  const normalizedMaxPlayers = Number.isInteger(maxPlayers) ? Number(maxPlayers) : 20
  const normalizedSpawnProtection = Number.isInteger(spawnProtection) ? Number(spawnProtection) : 16

  await mkdir(serverPath, { recursive: true })
  await writeFile(path.join(serverPath, "eula.txt"), "eula=true\n", "utf8")
  const propertiesText = [
    "# Generated by Norn",
    `server-port=${normalizedPort}`,
    `online-mode=${offlineMode ? "false" : "true"}`,
    `max-players=${normalizedMaxPlayers}`,
    `motd=${motd ?? "A Minecraft Server"}`,
    `pvp=${pvp === false ? "false" : "true"}`,
    `level-seed=${seed ?? ""}`,
    `difficulty=${difficulty ?? "normal"}`,
    `gamemode=${gamemode ?? "survival"}`,
    `allow-flight=${allowFlight ? "true" : "false"}`,
    `spawn-protection=${normalizedSpawnProtection}`
  ].join("\n")
  await writeFile(path.join(serverPath, "server.properties"), `${propertiesText}\n`, "utf8")

  const downloadUrl = await provider.getDownloadUrl(version, build)
  const jarRes = await fetch(downloadUrl)
  if (!jarRes.ok) {
    return json({ error: `Failed to download server jar: ${jarRes.status}` }, { status: 502 })
  }

  const jarData = Buffer.from(await jarRes.arrayBuffer())
  await writeFile(jarPath, jarData)

  const created = serverDb.createServer({
    id,
    name,
    jarPath,
    minMem: minMem && minMem.trim().length > 0 ? minMem.trim() : "1024M",
    maxMem: maxMem && maxMem.trim().length > 0 ? maxMem.trim() : "4096M",
    jvmArgs: jvmArgs?.trim() ?? "",
    host: "127.0.0.1",
    port: normalizedPort,
    offlineMode: offlineMode ?? false,
    maxPlayers: normalizedMaxPlayers,
    motd: motd ?? "A Minecraft Server",
    pvp: pvp ?? true,
    seed: seed ?? "",
    difficulty: difficulty ?? "normal",
    gamemode: gamemode ?? "survival",
    allowFlight: allowFlight ?? false,
    spawnProtection: normalizedSpawnProtection
  })

  return json(created, { status: 201 })
}
