import { json, type RequestHandler } from "@sveltejs/kit"
import { minecraftServerManager } from "$lib/server/minecraft-server-manager"
import { serverDb } from "$lib/server/db"
import path from "node:path"
import { writeFile } from "node:fs/promises"

export const GET: RequestHandler = async ({ params }) => {
  const serverId = params.id
  if (!serverId) {
    return json({ error: "Missing server id" }, { status: 400 })
  }

  const serverState = minecraftServerManager.getServerState(serverId)
  if (!serverState) {
    return json({ error: `Unknown server: ${serverId}` }, { status: 404 })
  }

  return json(serverState)
}

export const PUT: RequestHandler = async ({ params, request }) => {
  const serverId = params.id
  if (!serverId) {
    return json({ error: "Missing server id" }, { status: 400 })
  }

  const body = (await request.json()) as {
    name?: string
    minMem?: string
    maxMem?: string
    jvmArgs?: string
    host?: string
    port?: number
    offlineMode?: boolean
    maxPlayers?: number
    motd?: string
    pvp?: boolean
    seed?: string
    difficulty?: "easy" | "normal" | "hard" | "peaceful"
    gamemode?: "survival" | "creative" | "adventure" | "spectator"
    allowFlight?: boolean
    spawnProtection?: number
  }

  const updated = serverDb.updateServer(serverId, {
    name: body.name?.trim() || undefined,
    minMem: body.minMem?.trim() || undefined,
    maxMem: body.maxMem?.trim() || undefined,
    jvmArgs: body.jvmArgs?.trim() ?? undefined,
    host: body.host?.trim() || undefined,
    port: Number.isInteger(body.port) ? body.port : undefined,
    offlineMode: body.offlineMode,
    maxPlayers: Number.isInteger(body.maxPlayers) ? body.maxPlayers : undefined,
    motd: body.motd ?? undefined,
    pvp: body.pvp,
    seed: body.seed ?? undefined,
    difficulty: body.difficulty,
    gamemode: body.gamemode,
    allowFlight: body.allowFlight,
    spawnProtection: Number.isInteger(body.spawnProtection) ? body.spawnProtection : undefined
  })

  if (!updated) {
    return json({ error: `Unknown server: ${serverId}` }, { status: 404 })
  }

  const serverPath = path.dirname(updated.jarPath)
  const propertiesText = [
    "# Generated by Norn",
    `server-port=${updated.port ?? 25565}`,
    `online-mode=${updated.offlineMode ? "false" : "true"}`,
    `max-players=${updated.maxPlayers ?? 20}`,
    `motd=${updated.motd ?? "A Minecraft Server"}`,
    `pvp=${updated.pvp === false ? "false" : "true"}`,
    `level-seed=${updated.seed ?? ""}`,
    `difficulty=${updated.difficulty ?? "normal"}`,
    `gamemode=${updated.gamemode ?? "survival"}`,
    `allow-flight=${updated.allowFlight ? "true" : "false"}`,
    `spawn-protection=${updated.spawnProtection ?? 16}`
  ].join("\n")
  await writeFile(path.join(serverPath, "server.properties"), `${propertiesText}\n`, "utf8")

  minecraftServerManager.syncServerInfo(serverId, updated)
  return json(updated)
}
